alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline --graph --decorate'

alias ls='eza'
alias ll='eza -la --git'
alias la='eza -a'
alias l='eza -l'
alias tree='eza --tree'
alias cat='bat'
alias grep='rg'
alias find='fd'


